### ISSUE TITLE
Endpoint uncertainty & HTML errors 

### ISSUE THREAD

**Issue by MikeCodesDotNET** [NickSpag/MobileImmersiveReader#1]
Hey Nick, 

I've been trying to use your sample but face a few issues. First problem was not knowing what to include in the `ImmersiveReaderEndpoint` property of PrivateKeys.cs. After a little bit of trial and error I'm concluding that this should be something like: 
`https://eastus.api.cognitive.microsoft.com/sts/v1.0/issueToken`

Could you confirm? I'd also recommend just leaving your endpoints in and removing the API key as it removes any ambiguity for others trying to reuse this. 

With the API keys and endpoints set, I ran a test using the following images my source: 
`https://i.stack.imgur.com/sFPWe.png`

Looking at `recognitionResults` in the ReadPhoto method, it parses the text out of the image correctly and generates the following HTML (I've removed my token): 

```
<html>
   <head>
      <meta charset='utf-8'>
      <script type='text/javascript' src='https://contentstorage.onenote.office.net/onenoteltir/immersivereadersdk/immersive-reader-sdk.preview.js'></script>
   </head>
   <body onload='launchImmersiveReader()'>
      <div class='immersive-reader-button' data-button-style='iconAndText' onclick='launchImmersiveReader()'></div>
      <script type='text/javascript'>function launchImmersiveReader() {const content = {title: 'ImmersiverReader',chunks: [ {content: 'This is a lot of 12 point text to test the ocr code and see if it works on all types of file format. The quick brown dog jumped over the lazy fox. The quick brown dog jumped over the lazy fox. The quick brown dog jumped over the lazy fox. The quick brown dog jumped over the lazy fox. '}]};const token = 'TOKEN';ImmersiveReader.launchAsync(token, null, content);}</script>
   </body>
</html>
```

Loading the HTML into my desktop browser, I see two errors and three warnings. 

**Errors**
* Failed to load: learningtools.onenote.com/learningtoolsapi/cognitive/v2.0/GetContentModelForReader:1 Failed to load resource: the server responded with a status of 401 ()

* Uncaught (in promise) immersive-reader-sdk.preview.js:1 Uncaught (in promise) {code: "Timeout", message: "Page failed to load after timeout (15000 ms)"}

**On Device** 
When I test the app on device rather than the resulting HTML in a desktop browser, I don't get any text appear in the webview. 

**Thoughts**
This could be due to my earlier conclusion (*guess) at the valid endpoint, so clarity on this would be useful. If it's not due to that then could you please let me know if you've seen this in your testing?

**Comment by NickSpag** [comment]
Hey @MikeCodesDotNET, good to hear from ya!

Your assumption was correct. I pushed some changes to [PrivateKeys.cs](https://github.com/NickSpag/MobileImmersiveReader/blob/master/src/MobileImmersiveReader/Help/PrivateKeys.cs) to incorporate your feedback and make it a little more clear. I'm also going to push a more expanded update to the readme later today.

The latter is interesting and I'm going to try it shortly on my end. Since your endpoint was correct, those errors look specific to the javascript library, potentially some changes they pushed. As you can see I'm just injecting the public .js file in our own script, and there's probably a cleaner way to build their npm package and inject it in to our project or something. I'll report back and can talk to the team. Thanks for the feedback!

**Comment by NickSpag** [comment]
Hey @MikeCodesDotNET, could you try it again, but with a new token? I have a feeling that when you were doing your trial and error with the endpoint, the token expired. They are currently *very* short-lived. I took your script exactly and loaded it with a fresh token and it worked fine. I let it sit for 10 minutes and the errors you referenced popped up.

I'll update the code to more frequently refresh the token as well.

**Comment by MikeCodesDotNET** [comment]
Hey Nick! 

Thanks for clarifying the endpoint url, that helps confirm that I was moving in the right direction. 

I've had a little play again but this time using an API key from Brandon Minnick and its working! I'm slightly confused about why my API key is valid for creating a token but that requests with the resulting token fail so I'll dig into this!
